name: Build Android Release

on:
  push:
    tags:
      - 'v*.*'    
jobs:
  build_linux:
    name: Build linux client executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install
      - run: go build -o corpotecht_client
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: linux
          path: corpotecht_client
            

  build_windows:
    name: Build windows client executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install
      - run: go build -o corpotecht_client.exe
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: corpotecht_client.exe        
  release:
    name: Publish Release Images
    runs-on: ubuntu-latest
    needs: [build_linux,build_windows]
    permissions:
      packages: write
      contents: write
    steps:
    - name: Download Linux Build
      uses: actions/download-artifact@v2.1.0
      with:
        name: linux
        path: linux
    - name: Download Windows Build
      uses: actions/download-artifact@v2.1.0
      with:
        name: windows
        path: windows
    
    - name: Update GitHub Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: false
        name: ${{ github.ref_name }}
        token: ${{ github.token }}
        artifacts: 'linux/corpotecht_client,windows/corpotecht_client.exe'
      

