name: Build Android Release

on:
  push:
    tags:
      - 'v*.*'    


jobs:

  build_linux:
    name: Build linux client executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install
      - run: go build -o corpotecht_client
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            corpotecht_client
            

  build_windows:
    name: Build windows client executable
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install
      - run: go build -o corpotecht_client.exe
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            corpotecht_client.exe           
  
