name: Build Android Release

on:
  push:
    tags:
      - 'v*.*'    


jobs:

  build_linux:
    name: Build linux client executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install
      - run: go build -o corpotecht_client
      - uses: actions/upload-artifact@v3
        with:
          name: Linux Client
          path: corpotecht_client
            

  build_windows:
    name: Build windows client executable
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install
      - run: go build -o corpotecht_client.exe
      - uses: actions/upload-artifact@v3
        with:
          name: Windows Client
          path: corpotecht_client.exe        
  
